site_name: "Liquid Investigations Documentation"
site_author: "Liquid Investigations"

theme:
  name: material

markdown_extensions:
    - toc:
        permalink: "  #  "
nav:
    - Home: 'index.md'
    - 'User-Guide.md'
    - 'Technical-Overview.md'
    - 'Installation.md'
    - 'Maintenance.md'
    - 'Contributing.md'
plugins:
    - search
    - offline
    - roamlinks
